CASOS_DE_TESTE = [
    # 001 a 009: sessão launcher
    "Acessar o menu na tela inicial",
    "Acessar o menu pela tecla confirma",
    "Acessar todos os App's e voltar ao menu pelo touch",
    "Sair do menu e voltar para home",
    "Atualizar versão do launcher",
    "Acessar todos os App's e voltar ao menu pelo teclado fisico",
    "O botão redireciona para o pagamento",
    "Validar funções dos botões fisicos - Ajuda",
    "Validar funções dos botões fisicos - Ajustes",
    
    # 010 a 060: sessão pagamento
    "Realizar um pagamento - Débito - CHIP (Amount First)",
    "Realizar um pagamento - Débito - CHIP (Card First)",
    "Realizar um pagamento - Débito - TARJA (Amount First)",
    "Realizar um pagamento - Débito - NFC (Amount First)",
    "Realizar um pagamento - Crédito - CHIP (Amount First)",
    "Realizar um pagamento - Crédito - CHIP (Card First)",
    "Realizar um pagamento - Crédito  - TARJA (Amount First)",
    "Realizar um pagamento - Crédito - NFC (Amount First)",
    "Realizar um pagamento - Crédito Parcelado sem Juros - CHIP (Amount First)",
    "Realizar um pagamento - Crédito Parcelado sem Juros - CHIP (Card First)",
    "Realizar um pagamento - Crédito Parcelado sem Juros - TARJA (Amount First)",
    "Realizar um pagamento - Crédito Parcelado sem Juros - NFC (Amount First)",
    "Realizar um pagamento - Crédito Parcelado Emissor - CHIP (Amount First)",
    "Realizar um pagamento - Crédito Parcelado Emissor - CHIP (Card First)",
    "Realizar um pagamento - Crédito Parcelado Emissor - TARJA (Amount First)",
    "Realizar um pagamento - Crédito Parcelado Emissor - NFC (Amount First)",
    "Realizar Pagamento por FallBack",
    "Realizar um pagamento - Débito - CHIP (ID DO PEDIDO HABILITADO )",
    "Realizar um pagamento - Débito - TARJA (ID DO PEDIDO HABILITADO )",
    "Realizar um pagamento - Débito - NFC (ID DO PEDIDO HABILITADO )",
    "Realizar um pagamento - Crédito - CHIP (ID DO PEDIDO HABILITADO )",
    "Realizar um pagamento - Crédito - TARJA (ID DO PEDIDO HABILITADO )",
    "Realizar um pagamento - Crédito - NFC (ID DO PEDIDO HABILITADO )",
    "Realizar um pagamento - Parcelado sem juros   - CHIP (ID DO PEDIDO HABILITADO )",
    "Realizar um pagamento - Parcelado sem juros  - TARJA (ID DO PEDIDO HABILITADO )",
    "Realizar um pagamento - Parcelado sem juros  - NFC (ID DO PEDIDO HABILITADO )",
    "Realizar um pagamento - Parcelado emissor  - CHIP (ID DO PEDIDO HABILITADO )",
    "Realizar um pagamento - Parcelado emissor   - TARJA (ID DO PEDIDO HABILITADO )",
    "Realizar um pagamento - Parcelado emissor   - NFC (ID DO PEDIDO HABILITADO )",
    "Realizar um pagamento com valor acima de 200 reais via NFC",
    "Realizar um pagamento - Voucher",
    "Realizar um pagamento em dinheiro",
    "Calcular troco pagamento em dinheiro",
    "Impressão via lojista (Debito/Credito/Credito a vista/ Qrcode / Pix / Voucher)",
    "Impressão via do cliente (Debito/Credito/Credito a vista/ Qrcode / Pix/ Voucher)",
    "Envio do comprovante pagamento via SMS (Debito/Credito/Credito a vista/ Qrcode / Pix /Voucher)",
    "Impressão via lojista/cliente pagamento em dinheiro",
    "Gerar e Pagar QrCode Débito via 3G/4G",
    "Gerar e Pagar QrCode Débito via Wifi",
    "Gerar e Pagar Qrcode Crédito via 3G/4G",
    "Gerar e Pagar Qrcode Crédito via Wifi",
    "Gerar e Pagar Qrcode Credito Parcelado via 3G/4G",
    "Gerar e Pagar Qrcode Credito Parcelado via Wifi",
    "Gerar e Pagar Pix via Wifi",
    "Gerar e Pagar Pix via 3G/4G", 
    "Digitar senha incorreta cartão PIN ONLINE",
    "Digitar senha incorreta cartão PIN OFFLINE",
    "Digitar senha incorreta cartão Tarja",
    "Digitar senha incorreta cartão NFC",
    "Realizar transação com cartão sem saldo",
    "Realizar transação com cartão bloqueado",
    
    # 061 a 071: Seção Cancelamento
    "Validar senha ADM incorreta no Cancelamento",
    "Validar senha ADM correta no Cancelamento",
    "Visualizar senha ADM no Cancelamento",
    "Transação não encontrada",
    "Cancelar uma transação de cartão com sucesso",
    "Cancelar uma transação Qrcode com sucesso",
    "Cancelar uma transação Pix com sucesso",
    "Cancelar uma transação Parcelada com sucesso",
    "Cancelar uma transação Voucher com sucesso",
    "Impressão via cliente",
    "Impressão via lojista",
    
    # 072 a 086: Seção Conexão
    "Consultar redes Wifi disponíveis",
    "Conectar em uma rede Wifi",
    "Mudar rede Wifi",
    "Esquecer rede Wifi",
    "Conectar rede Wifi por senha incorreta",
    "Conectar rede Wifi por ausência de sinal",
    "Conectar em uma rede Wifi Salva",
    "Reconexão rede Wifi",
    "Reconexão rede 3G/4G",
    "Troca de rede Wifi para 3G/4G durante falha de conexão",
    "Troca de rede 3G/4G para Wifi durante falha de conexão",
    "Troca de rede Wifi para 3G/4G durante Pagamento",
    "Troca de rede 3G/4G para Wifi durante Pagamento",
    "Troca de rede Wifi para 3G/4G durante Cancelamento",
    "Troca de rede 3G/4G para Wifi durante Cancelamento",

    # 087 a 097: Seção Ativação
    "Ativar POS via Wifi",
    "Ativar POS via 3G/4G",
    "Falha ativação POS via Wifi",
    "Falha ativação POS via 3G/4G",
    "Falha ativação POS SC/Codigo Ativação Incorreto",
    "Troca de rede Wifi para 3G/4G durante ativação",
    "Troca de rede 3G/4G para Wifi durante ativação",
    "Cadastrar senha válida na ativação",
    "Cadastrar senha inválida na ativação (exibição de senha invalida na tentativa)",
    "Falha ao conectar no Wifi",
    "Falha ao conectar no 3G/4G",

    # 098 a 113: Seção Ajustes
    "Validar fluxo de configuração de rede Wifi",
    "Validar digitação senha Wifi pelo teclado físico",
    "Validar digitação senha Wifi pelo teclado virtual",
    "Ativar/desativar som do teclado",
    "Ativar/desativar luz do teclado",
    "Validar função bloqueio de Apps",
    "Habilitar aplicativo Inicial",
    "Configurar Brilho de tela",
    "Habilitar/Desabilitar via lojista",
    "Habiltar/Desabilitar QrCode",
    "Habilitar/Desabilitar Frase no Recibo",
    "Habilitar/Desabilitar ID do Pedido",
    "Habilitar/Desabilitar Parcelado Emissor",
    "Validar Restauração de Dados",
    "Alterar senha ADM",
    "Configurar Modo de Descanso",

    # 114 a 121: Seção Ajuda
    "Consultar aba 'Fale Conosco'",
    "Consultar aba 'Detalhes da Maquina'",
    "Consultar aba 'Dúvidas Frequentes'",
    "Acessar Ajuda via teclado físico",
    "Acessar Ajuda via menu",
    "Acessar 'Ultimos erros' sem ocorrência de erros",
    "Acessar 'Ultimos erros' com ocorrência de erros",
    "Imprimir 'Ultimos erros'",

    # 122 a 124: Seção Calculadora
    "Realizar operações matemáticas",
    "Realizar pagamento a partir do calculo obtido",
    "Realizar pagamento a partir de valor inserido",

    # 125 a 132: Seção Simulador de Vendas
    "Abrir/Fechar Simulador de Vendas pelo touch",
    "Abrir/Fechar Simulador de Vendas pelo teclado físico",
    "Simular Venda no Débito",
    "Simular Venda no Crédito",
    "Simular Venda no Credito Parcelado",
    "Ativar/Desativar 'receber valor integral'",
    "Simular Vendas em 13x a 18x",
    "Realizar pagamento Debito/Credito/Credito Parcelador a partir do Simulador de Vendas",

    # 133 a 141: Seção Reimpressão/Recibos
    "Reimpressão recibo de pagamento anterior a atualização",
    "Reimpressão recibo de cancelamento anterior a atualização",
    "Reimpressão recibo via lojista não impressa no pagamento",
    "Reimpressão recibo via cliente não impressa no pagamento",
    "Reimpressão recibo via lojista não impressa no cancelamento",
    "Reimpressão recibo via cliente não impressa no cancelamento",
    "Reenvio SMS do pagamento",
    "Reenvio SMS do cancelamento",
    "POS sem transação disponivel",

    # 142 a 150: Seção Relatório 
    "Consultar transação na data atual no relatório consolidado e detalhado",
    "Consultar transações antigas no relatório consolidado e detalhado",
    "Verificar se transações no relatório mantem após atualização",
    "Imprimir relatório detalhado",
    "Imprimir relatório consolidado",
    "Imprimir relatório de vendas das ultimas 45 transações",
    "Enviar relatório por e-mail consolidado e detalhado",
    "Validar que vendas apareçam no Relatório (Debito/Credito/Credito a vista/ Qrcode / Pix/ Voucher)",
    "Validar que vendas em dinheiro apareçam no Relatório",

    # 151 a 156: Seção Fechamento 
    "Realizar primeiro fechamento do POS com data e horarios incorretos",
    "Realizar primeiro fechamento do POS com data e horarios validos",
    "Realizar um fechamento qualquer",
    "Consultar fechamentos disponiveis",
    "Imprimir fechamento",
    "Imprimir fechamento sem papel",

    # 157 a 161: Seção Loja 
    "Exibição app Loja no menu",
    "Listar apps disponiveis para instalar",
    "Instalar um app Não nativo",
    "Tentar desinstalar um app Nativo",
    "Verificar se apps instalados não nativos mantém após atualizar sistema",

    # 162 a 164: Seção Novidades 
    "Novidades abrindo após ativação do terminal",
    "Novidades abrindo após atualização do kernel",
    "Abri app novidades pelo menu"
]

PASSOS_EXECUCAO = [
    # 001 a 009 (Seção launcher)
    "Na tela inicial do POS > Clicar no botão de MENU.",
    "Na tela inicial do POS > Clicar no botão Enter do teclado.",
    "Acessar o menu > Selecionar um aplicativo da lista > Clicar no botão  na seta superior do app para retornar à tela de menu do POS.",
    "Acessar o menu > Clicar na seta até volta para retornar à tela inicial do POS.",
    "Acessar o menu e selecionar o aplicativo de Ajustes > Selecionar a opção > Verificar Atualização > verificar atualização > O terminal irá instalar automaticamente a nova versão disponível do launcher.",
    "Acessar o menu > Selecionar um aplicativo da lista > Clicar na seta  para retornar ao menu.",
    "Na tela inicial do POS > Clicar em  pagamentos > Deverá ser aberto o aplicativo de pagamento.",
    "Validar botões funções dos botões fisicos.",
    "Validar botões funções dos botões fisicos.",
    
    # 010 a 060 (Seção Pagamento)
    "Abrir o Aplicativo de Pagamento > Digitar o valor da venda e aperte OK  > Selecionar a opção débito > Aproximar ou Inserir o Cartão e Realizar a venda.",
    "Inserir o Cartão na maquininha >  Digitar o valor da venda e aperte OK >Selecionar a opção débito e aperte o botão verde no teclado >  Realizar a venda.",
    "Abrir o Aplicativo de Pagamento > Digitar o valor da venda e aperte OK  > Selecionar a opção débito >Passar a tarja do cartão no local indicado e Realizar a venda.",
    "Abrir o Aplicativo de Pagamento > Digitar o valor da venda e aperte OK  > Selecionar a opção débito > Aproximar o Cartão e Realizar a venda.",
    "Abrir o Aplicativo de Pagamento > Digitar o valor da venda e aperte OK  > Selecione a opção Crédito > Seleciona a Opção à Vista > Inserir o Cartão e Realizar a venda.",
    "Inserir o Cartão na maquininha > Digitar o valor da venda e aperte o botão verde no teclado  > Selecione a opção Crédito > Selecionar a Opção à Vista Realizar a venda.",
    "Abrir o Aplicativo de Pagamento > Digitar o valor da venda e aperte OK  > Selecionar a opção Crédito > Selecionar a Opção à Vista > Passar a tarja do cartão no local indicado e Realizar a venda.",
    "Abrir o Aplicativo de Pagamento > Digitar o valor da venda e aperte OK  > Selecionar a opção crédito> Selecionar a Opção à Vista >  Aproximar o Cartão e Realizar a venda.",
    "Abrir o Aplicativo de Pagamento > Digitar o valor da venda e aperte OK  > Selecionar a opção Crédito> Selecionar a Opção à Parcelado sem juros > Informar a quantidade de parcelas >Inserir o Cartão e Realizar a venda.",
    "Inserir o Cartão na maquininha > Digitar o valor da venda > Selecionar a modalidade Crédito  > Seleciona a Opção à Parcelado sem juros Informar a quantidade de parcelas > e aperte o botão verde no teclado > Realizar a venda.",
    "Abrir o Aplicativo de Pagamento > Digitar o valor da venda e aperte OK  > Selecionar a opção Crédito > Selecionar Opção à Parcelado sem juros > Informar a quantidade de parcelas > Passar a tarja do cartão no local indicado e Realizar a venda.",
    "Abrir o Aplicativo de Pagamento > Digitar o valor da venda e aperte OK  > Selecionar a opção crédito> Selecionar  Opção à Parcelado sem juros > Informar a quantidade de parcelas >  Aproximar o Cartão e Realizar a venda.",
    "Abrir o Aplicativo de Pagamento > Digitar o valor da venda e aperte OK  > Selecionar a opção Crédito> Selecionar a Opção à Parcelado com juros> Informar a quantidade de parcelas >Inserir o Cartão e Realizar a venda.",
    "Inserir o Cartão na maquininha >Digitar o valor da venda e aperte OK  > Selecionar a opção Crédito> Selecionar a Opção à Parcelado com juros > Informar a quantidade de parcelas> Digitar o valor da venda e aperte o botão verde no teclado > Realizar a venda.",
    "Abrir o Aplicativo de Pagamento > Digitar o valor da venda e aperte OK  > Selecionar a opção Crédito > Seleciona a Opção à Parcelado Emissor  > Informar a quantidade de parcelas > Passar a tarja do cartão no local indicado.",
    "Abrir o Aplicativo de Pagamento > Digitar o valor da venda e aperte OK  > Selecionar a opção crédito> Seleciona a Opção à Parcelado Emissor  > Informar a quantidade de parcelas >  Aproximar o Cartão e Realizar a venda.",
    "Inserir o cartão com erro  na maquininha 3 vezes seguidas > Aguardar a mensagem \"Erro ao ler o cartão. Utilize a tarja magnética ou Inserir o cartão novamente\" ser exibida na tela > Passar o cartão com tarja magnética no local indicado > Selecionar uma opção de pagamento > Digitar o valor e realizar a venda.",
    "Abrir o aplicativo de Ajustes > Habilitar a opção \"ID do Pedido\" > Inserir o cartão com CHIP > Digitar o valor da venda e apertar o botão verde do teclado >  Digitar o código ID do pedido e confirmar > Selecionar a opção Débito >   Realizar a venda.",
    "Abrir o aplicativo de Ajustes > Habilitar a opção \"ID do Pedido\" > Passar o cartão com a Tarja magnética no local indicado > Digitar o valor da venda e apertar o botão verde do teclado >   Digitar o código ID do pedido e confirmar > Selecionar a opção Débito >  Digitar o valor da venda e apertar o botão verde do teclado > Realizar a venda.",
    "Abrir o aplicativo de Ajustes > Habilitar a opção \"ID do Pedido\" > Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Digitar o código ID do pedido e confirmar > Selecionar a opção Débito > Realizar a venda.",
    "Abrir o aplicativo de Ajustes > Habilitar a opção \"ID do Pedido\" > Inserir o cartão com CHIP >  Digitar o código ID do pedido e confirmar > Selecionar a opção Crédito > Selecionar a opção Crédito à Vista > Digitar o valor da venda e apertar o botão verde do teclado > Realizar a venda.",
    "Abrir o aplicativo de Ajustes > Habilitar a opção \"ID do Pedido\" > Passar o cartão com a Tarja magnética no local indicado >  Digitar o código ID do pedido e confirmar > Selecionar a opção Crédito > Selecionar a opção Crédito à Vista > Digitar o valor da venda e apertar o botão verde do teclado > Realizar a venda.",
    "Abrir o aplicativo de Ajustes > Habilitar a opção \"ID do Pedido\" > Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Digitar o código ID do pedido e confirmar > Selecionar a opção Crédito à Vista > Realizar a venda.",
    "Abrir o aplicativo de Ajustes > Habilitar a opção \"ID do Pedido\" > Inserir o cartão com CHIP >  Digitar o código ID do pedido e confirmar > Selecionar a opção Crédito > Selecionar a opção Crédito Parcelado Sem Juros > Informar a quantidade de parcelas > Digitar o valor da venda e apertar o botão verde do teclado > Realizar a venda.",
    "Abrir o aplicativo de Ajustes > Habilitar a opção \"ID do Pedido\" > Passar o cartão com a Tarja magnética no local indicado >  Digitar o código ID do pedido e confirmar > Selecionar a opção Crédito Parcelado Sem Juros > Informar a quantidade de parcelas > Digitar o valor da venda e apertar o botão verde do teclado > Realizar a venda.",
    "Abrir o aplicativo de Ajustes > Habilitar a opção \"ID do Pedido\" > Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Digitar o código ID do pedido e confirmar > Selecionar a opção Crédito Parcelado Sem Juros > Informar a quantidade de parcelas> Realizar a venda.",
    "Abrir o aplicativo de Ajustes > Habilitar a opção \"ID do Pedido\" > Inserir o cartão com CHIP >  Digitar o código ID do pedido e confirmar > Selecionar a opção Crédito > Selecionar a opção Crédito Parcelado com juros > Informar a quantidade de parcelas > Digitar o valor da venda e apertar o botão verde do teclado > Realizar a venda.",
    "Abrir o aplicativo de Ajustes > Habilitar a opção \"ID do Pedido\" > Passar o cartão com a Tarja magnética no local indicado > Digitar o valor da venda e apertar o botão verde do teclado > Digitar o código ID do pedido e confirmar > Selecionar a opção Crédito > Parcelado com juros > Informar a quantidade de parcelas > > Realizar a venda.",
    "Abrir o aplicativo de Ajustes > Habilitar a opção \"ID do Pedido\" > Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Digitar o código ID do pedido e confirmar > Selecionar a opção Crédito Parcelado parcelado com \"Juros\"  > Informar a quantidade de parcelas> Realizar a venda.",
    "Abrir o aplicativo de Pagamento > Digitar o valor de uma venda acima de R$200,00 e apertar o botão verde do teclado > Selecionar a forma de pagamento > Aproximar o cartão NFC > Solicitar a senha do cliente e realizar a venda.",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a opção de pagamento Voucher > Aproximar ou inserir o cartão e realizar a venda.",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a opção de pagamento Dinheiro > Digitar o valor received em dinheiro > Clicar em \"Registrar o Pagamento\" para confirmar e finalizar venda.",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a opção de pagamento Dinheiro > Digitar o valor recebido em dinheiro > Digitar o valor do troco a ser devolvido > Clicar em \"Registrar o Pagamento\" para confirmar e finalizar venda.",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a forma de pagamento > Aproximar ou inserir o cartão e realizar a venda > O sistema irá imprimir o comprovante após a aprovação do pagamento contendo as seguintes informações : Tipo da Filipeta (Lojista), Local da transação, Logo da Stone, Nome Fantasia do Lojista, Data e hora, CNPJ do Lojista,Tipo de Transação, Valor da Transação, Nome do Cartão/Titular, Serial Number do POS (13 dígitos) e versão StoneID (se tiver possuir).",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a forma de pagamento > Aproximar ou inserir o cartão e realizar a venda > O sistema irá imprimir o comprovante após a via do lojista contendo as seguintes informações : Tipo da Filipeta (Cliente),) Local da transação, Logo da Stone, Nome Fantasia do Lojista, Data e hora, CNPJ do Lojista, Tipo de Transação, Valor da Transação, Nome do Cartão/Titular, Serial Number do POS  (13 dígitos) e versão StoneID (se possuir).",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a forma de pagamento > Aproximar ou inserir o cartão e realizar a venda > O sistema irá imprimir o comprovante após a via do lojista contendo as seguintes informações : Tipo da Filipeta (Cliente),) Local da transação, Logo da Stone, Nome Fantasia do Lojista, Data e hora, CNPJ do Lojista, Tipo de Transação, Valor da Transação, Nome do Cartão/Titular, Serial Number do POS  (7 dígitos) e versão StoneID (se possuir).",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a opção de pagamento Dinheiro > Realizar a venda > O sistema irá imprimir o comprovante após a aprovação do pagamento contendo as seguintes informações : Tipo da Filipeta (Lojista), Local da transação, Logo da Stone, Nome Fantasia do Lojista, Data e hora, CNPJ do Lojista,Tipo de Transação, Valor da Transação, Nome do Cartão/Titular, Serial Number do POS (7 dígitos) e versão StoneID (se tiver possuir).",
    "Acessar o aplicativo de Ajustes > Selecionar a opção \"Configurar Wi-Fi\" > Selecionar a opção \"Trocar para Redes Móveis\" > Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a opção de pagamento QR Code > Selecionar a opção Débito > Realizar a leitura do QR Code na tela com a camera do celular e finalizar venda.",
    "Acessar o aplicativo de Ajustes > Selecionar a opção \"Configurar Wi-Fi\" > Selecionar a opção \"Trocar para Wi-fi\" > Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a opção de pagamento QR Code > Selecionar a opção Débito > Realizar a leitura do QR Code na tela com a camera do celular e finalizar venda.",
    "Acessar o aplicativo de Ajustes > Selecionar a opção \"Configurar Wi-Fi\" > Selecionar a opção \"Trocar para Redes Móveis\" > Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a opção de pagamento QR Code > Selecionar a opção Crédito > Selecionar a opção Crédito à Vista > Realizar a leitura do QR Code na tela com a camera do celular e finalizar venda.",
    "Acessar o aplicativo de Ajustes > Selecionar a opção \"Configurar Wi-Fi\" > Selecionar a opção \"Trocar para Wi-fi\" > Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a opção de pagamento QR Code > Selecionar a opção Crédito > Selecionar a opção Crédito à Vista > Realizar a leitura do QR Code na tela com a camera do celular e finalizar venda.",
    "Acessar o aplicativo de Ajustes > Selecionar a opção \"Configurar Wi-Fi\" > Selecionar a opção \"Trocar para Redes Móveis\" > Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a opção de pagamento QR Code > Selecionar a opção Crédito > Selecionar a opção Parcelado sem Juros > Informar o número de parcelas >  Realizar a leitura do QR Code na tela com a camera do celular e finalizar venda.",
    "Acessar o aplicativo de Ajustes > Selecionar a opção \"Configurar Wi-Fi\" > Selecionar a opção \"Trocar para Wi-fi\" > Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a opção de pagamento QR Code > Selecionar a opção Crédito > Selecionar a opção Parcelado sem Juros > Informar o número de parcelas >  Realizar a leitura do QR Code na tela com a camera do celular e finalizar venda.",
    "Acessar o aplicativo de Ajustes > Selecionar a opção \"Configurar Wi-Fi\" > Selecionar a opção \"Trocar para Wi-fi\" > Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a opção de pagamento PIX > Realizar a leitura do QR Code na tela com a camera do celular e finalizar venda.",
    "Acessar o aplicativo de Ajustes > Selecionar a opção \"Configurar Wi-Fi\" > Selecionar a opção \"Trocar para Redes Móveis\" >Abrir o aplicativo de Pagamento > Digitar o valor da venda e apertar o botão verde do teclado > Selecionar a opção de pagamento PIX > Realizar a leitura do QR Code na tela com a camera do celular e finalizar venda.",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda apertar e o botão verde do teclado > Selecionar a forma de pagamento > Inserir o cartão e digitar a senha incorreta > O sistema deverá exibir uma  notificação de senha incorreta após enviar a transação.",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda apertar e o botão verde do teclado > Selecionar a forma de pagamento > Inserir o cartão e digitar a senha incorreta > O sistema deverá exibir uma notificação de senha incorreta.",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda apertar e o botão verde do teclado > Selecionar a forma de pagamento > Passar a tarja do cartão no local indicado e digitar a senha incorreta > O sistema deverá exibir uma notificação de senha incorreta após enviar a transação.",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda apertar e o botão verde do teclado > Selecionar a forma de pagamento > Aproximar o cartão e digitar a senha incorreta > O sistema deverá exibir a mensagem de senha incorreta após enviar a transação.",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda apertar e o botão verde do teclado > Selecionar a forma de pagamento > Inserir ou aproximar o cartão com saldo inferior ao valor do pagamento > O sistema deverá exibir a mensagem de pagamento não aprovado após enviar a transação.",
    "Abrir o aplicativo de Pagamento > Digitar o valor da venda apertar e o botão verde do teclado > Selecionar a forma de pagamento > Inserir ou aproximar o cartão bloqueado > O sistema deverá exibir a mensagem de cartào bloqueado após enviar a transação.",
    
    # 061 a 071 (Seção Cancelamento)
    "Abrir o aplicativo Cancelamento > Ao abrir verificar o acesso digitando uma senha adminstrativa diferente da cadastrada > Deve aparecer uma mensagem de senha incorreta",
    "Abrir o aplicativo Cancelamento > Ao abrir verificar o acesso digitando a senha administrativa cadastrada > Deve-se ir para a tela de inserir/aproximar ou passar a tarja do cartão",
    "Abrir o aplicativo Cancelamento > Ao abrir a senha deve vir ocultada > Digitar a senha cadastrada > e clicar na opção para visualizar a senha adminstrativa > A senha deve ser mostrada",
    "Abrir o aplicativo Cancelamento > Ao abrir digitar a senha administrativa cadastrada > utilizar um cartão via tarja/chip ou NFC o qual não tenha sido realizada transação neste terminal > Deverá aparecer a mensagem de não existe transações para esse cartão",
    "Abrir o aplicativo Cancelamento >  Ao abrir digitar a senha adminstrativa cadastrada > Utilizar NFC/ Tarja ou chip para localizar a transação > efetuar o cancelamento da transação",
    "Abrir o aplicativo Cancelamento > Ao abrir digitar a senha administrativa cadastrada > deverá aparecer a opção de cancelamento digitando o StoneID  (deverá ter sido feita uma transação Qrcode > Digitar o Stone ID > Cancelar a transação",
    "Abri o aplicativo Cancelamento > Ao abrir digitar a senha administrativa cadastrada > Não deve ser possivel cancelar uma transação Pix",
    "Abrir o aplicativo Cancelamento > Ao abrir digitar a senha administrativa cadastrada > Utilziar NFC / Tarja ou chip para localizar a transação (deve ter sido realizada uma transação credito parcelado) > cancelar a transação credito parcelada",
    "Abrir o aplicativo Cancelamento > Ao abrir digitar a senha administrativa cadastrada > Utilziar NFC / Tarja ou chip para localizar a transação (deve ter sido realizada uma transação voucher) > cancelar a transação voucher",
    "Após realizar o fluxo de cancelamento > Imprimir a via do cliente",
    "Após realizar o fluxo de cancelamento > Imprimir a via do lojista",
    
    # 072 a 086 (Seção Conexão)
    "Abrir o aplicativo Ajustes > Rede Wi-fi ConfiguraWi-fi > Selecionar Wi-fi > Verificar se é listado redes Wi-fi disponíveis",
    "Abrir o aplicativo Ajustes > Rede Wi-fi ConfiguraWi-fi > Selecionar Wi-fi > Aguardar listagem de redes Wi-fi disponíveis > Selecionar uma rede e conectar com sucesso",
    "*Deverá estar conectado e salvo em duas redes Wi-fi > Após isso entrar no Abrir o aplicativo Ajustes > Rede Wi-fi ConfiguraWi-fi > Selecionar Wi-fi> Estando conectado a uma rede Wi-fi, deverá trocar de rede",
    "Abrir o aplicativo Ajustes > Rede Wi-fi ConfiguraWi-fi > Selecionar Wi-fi > Entrar em uma rede salva e clicar em \"Esquecer\"",
    "Abrir o aplicativo Ajustes > Rede Wi-fi ConfiguraWi-fi > Selecionar Wi-fi > Aguardar listagem de redes Wi-fi disponíveis > Selecionar uma rede > digitar a senha inválida da rede > devera mostrar uma mensagem de erro de senha",
    "Abrir o aplicativo Ajustes > Rede Wi-fi ConfiguraWi-fi > Selecionar Wi-fi > Aguardar listagem de redes Wi-fi disponíveis > Selecionar uma rede > digitar a senha valida da rede > Durante a conexão deverá ser desativado a rede Wi-fi no modem ou hotspot > o terminal deverá voltar para a listagem de redes wi-fi disponíveis.",
    "Abrir o aplicativo Ajustes > Rede Wi-fi ConfiguraWi-fi > Selecionar Wi-fi > Entrar em uma rede salva e clicar em Conectar",
    "Dado que estou conectado em uma rede Wi-fi > Desligar o roteador ou hotspot > O terminal perderá conexão > Ligar novamente o roteador ou hotspot > O terminal deverá reconectar automaticamente na rede",
    "Dado que estou conectado a uma rede movel > Simular uma falha de conexão no terminal > O terminal perderá conexão > Ligar novamente a conexão movel > O terminal deverá reconectar automaticamente na rede movel",
    "Dado que estou conectado a uma rede Wifi como prioridade > devo simular uma falha de conexão na rede Wi-fi e o terminal deverá ficar com a rede movel (3G) como prioridade.",
    "Dado que estou conectado a uma rede movel (3G) como prioridade > devo simular uma falha de conexão na rede 3G e o terminal deverá ficar com a rede Wifi como prioridade (status bar ficará com o Wifi verde)",
    "Abrir aplicativo de Pagamento > ir até a tela de senha > quando estiver na tela de senha, deverá simular uma falha no Wifi > digitar a senha e clicar no botão verde do teclado físico para enviar a transação > durante o Envio/ recebimento da transação deverá ser feita a troca de rede para 3G e a transação devera concluir",
    "Abrir aplicativo de Pagamento > ir até a tela de senha > quando estiver na tela de senha, deverá simular uma falha no 3G > digitar a senha e clicar no botão verde do teclado físico para enviar a transação > durante o Envio/ recebimento da transação deverá ser feita a troca de rede para o Wifi e a transação devera concluir",
    "Abrir o aplicativo de Cancelamento > digitar a senha administrativa > localizar a transação a ser cancelada > simular falha de rede Wifi > Clicar logo em seguida para cancelar a transação > Com isso o terminal deverá efetuará a troca do Wifi para o 3G",
    "Abrir o aplicativo de Cancelamento > digitar a senha administrativa > localizar a transação a ser cancelada > simular falha de rede 3G > Clicar logo em seguida para cancelar a transação > Com isso o terminal deverá efetuar a troca do 3G para o Wifi",

    # 087 a 097 (Seção Ativação)
    "Após o POS ligar na tela de Ativação > selecionar e conectar em uma rede Wifi > digitar o Stonecode e ativar o POS estando na rede Wifi.",
    "Após o POS ligar na tela de Ativação > selecionar a opção 3G > digitar o Stonecode e ativar o POS estando na rede 3G.",
    "Após o POS ligar na tela de Ativação > selecionar e conectar em uma rede Wifi > digitar o Stonecode > e antes de clicar para ativar, simular uma falha no Wifi > Com isso o terminal resultara em uma falha na ativação (terminal devera estar apenas conectado no Wifi).",
    "Após o POS ligar na tela de Ativação > selecionar a opção 3G > digitar o Stonecode > e antes de clicar para ativar , simular uma falha na rede 3G > Com isso o terminal resultara em uma falha na ativação (terminal devera estar apenas conectado no 3G).",
    "Após o POS ligar na tela de Ativação > selecionar e conectar em uma rede Wifi > digitar o Stonecode invalido (por exemplo: 000000000) e Clicar para ativar > Com isso aparecerá uma mensagem de erro de Stonecode invalido.",
    "Após o POS ligar na tela de Ativação > selecionar e conectar em uma rede Wifi > digitar o Stonecode > e antes de clicar para ativar, simular uma falha no Wifi > Com isso o terminal irá trocar da rede Wifi para o 3G e conseguir ativar.",
    "Após o POS ligar na tela de Ativação > selecionar a opção 3G > digitar o Stonecode > e antes de clicar para ativar , simular uma falha na rede 3G > Com isso o terminal irá trocar da rede 3G para o Wifi e conseguira ativar (Antes de selecionar a oção 3G devera conectar a uma rede Wifi e retornar e acessar pelo 3G).",
    "Após o POS ligar na tela de Ativação > selecionar e conectar em uma rede Wifi  ou 3G > digitar o Stonecode e ativar o POS  > Após impressão da filipeta de ativação o terminal deverá aparecer para criar uma senha Wifi (criar senha sem possuir numero sequenciais ou repetidos).",
    "Após o POS ligar na tela de Ativação > selecionar e conectar em uma rede Wifi  ou 3G > digitar o Stonecode e ativar o POS  > Após impressão da filipeta de ativação o terminal deverá aparecer para criar uma senha Wifi > tentar colocar numeração sequencial ou repetida (ex: 1234 ou 1111).",
    "Após o POS ligar na tela de Ativação > selecionar uma rede Wifi > deverá simular uma falha enquanto estiver conectando > com isso o terminal não devera conectar com o wi-fi.",
    "Após o POS ligar na tela de Ativação > selecionar a opção 3G > deverá simular uma falha enquanto estiver conectando > com isso o terminal não devera conectar com o 3G/4G.",

    # 098 a 113 (Seção Ajustes)
    "Abrir o aplicativo Ajustes >  Rede Wi-fi ConfiguraWi-fi >  Selecionar Wi-fi  > Verificar se é listado redes Wi-fi disponiveis > conectar a uma rede Wifi.",
    "No momento de digitar a senha do wifi > digitar pelo teclado fisico.",
    "No momento de digitar a senha do Wifi > digitar pelo teclado virtual que aparecem em terminais com tela grande com Touch.",
    "Abrir o aplicativo Ajustes > selecionar a opção 2 'Som do teclado' > desativa-lo e ativa-lo para validar a funcionalidade do som ao digitar (se é emitido quando ativado e se fica mudo quando desativado).",
    "Abrir o aplicativo Ajustes > seleiconar a opção 3 'Luz do teclado' > desativar e ativar e validar se a luz do teclado apaga e ascende.",
    "Abrir o aplicativo Ajustes > Dispositivo Bloqueio de Aplicativos >  ativar o bloqueio para algum app listado > clicar em salvar>digitar a senha > após ativar o bloqueio, abrir este mesmo app e verificar se pedirá senha administrativa ao inicia-lo.",
    "Para realizar este teste deverá ter sido feito download de um app no aplicativo +Apps > Após isso abrir o aplicativo ajustes > opção 5 - Aplicativo Inicial >  e Selecionar o aplicativo baixado > após habilitado reiniciar o terminal e verificar se o aplicativo inicia ao ligar o POS.",
    "Abrir aplicativo Ajustes > opção 6 - Energia > opção 1 - Brilho da tela > configurar o brilho da tela pelo touch e/ou teclado fisico.",
    "Abrir aplicativo Ajustes >  vendas> imprimir via lojista > Desativar a via do Estabelecimento > após isso realizar um pagamento verificar se a via do lojista deixará de ser impressa e o  cancelamento deverá ser impressa .",
    "Abrir aplicativo Ajustes > opção Meios de Pagamento > Digitar a senha administrativa > ativar/desativar o toggle do QR CODE > Após isso verificar se ele aparece / desaparece do aplicativo Pagamento quando iniciado o fluxo.",
    "Abrir o aplicativo Ajustes > Opção 0 - Recibos > Habilitar Frase do Recibo > Escrever uma frase pelo teclado fisico e/ou pelo touch > Após isso realizar um pagamennto e verificar se aparecerá a frase no Recibo do Pagamento > após isso desabilitar e verificar novamente se sumirá a frase.",
    "Abrir o aplicativo Ajustes > Opção ID do Pedido > ativar o toggle > após isso abrir o aplicativo Pagamento > e verificar se a opção ID do Pedido aparece no fluxo > Realizar um pagamento digitando um numero qualquer no ID do Pedido e validar se é impresso na filipeta.",
    "Abrir o aplicativo Ajustes > Opção Meios de pagamento >  opção 1 - Pagamento Parcelado > ativar o parcelado Emissor > selecionar também uma quantidade de parcelas que deseja permitir> abrir o aplicativo pagamento opção credito parcelado e realizar um pagamento parcelado emissor.",
    "Abrir o aplicativo Ajustes > opção Restaurar dados > digitar o numero incorretamente e verificar se irá aparecer a mensagem de erro 'Numero incorreto' > após isso digitar corretamente > terminal irá reiniciar e iniciará na tela de ativação.",
    "Abrir o aplicativo Ajustes > opção - Alterar senha > digitar a senha antiga e uma senha nova valida > verificar se senha foi alterada abrindo um app bloqueado (ex: aplicativo Cancelamento).",
    "Abrir o aplicativo Ajustes > Opção 6 - Energia > opção 2 Modo descanso > voltar o terminal para a tela inicial > verificar se no tempo selecionado quando ativado se o terminal entrará em modo de descanso.",

    # 114 a 121 (Seção Ajuda)
    "Abrir o aplicativo Ajuda > Selecionar a opção fale conosco > deverá abrir as informações de contato com a Stone/Ton.",
    "Abrir o aplicativo Ajuda > selecionar a opção Detalhes da Maquina > Deverá abrir as informações sobre o modelo.",
    "Abrir o aplicativo Ajuda > Deverá aparecer a opção duvidas frequentes abaixo > clicar em todas as oções > verificar se aparecem as informações.",
    "Abrir o aplicativo Ajuda através do botão no teclado físico escrito 'Ajuda'.",
    "Abrir o Menu > Abrir o aplicativo ajuda localizado no menu.",
    "Abrir o aplicativo Ajuda > Selecionar a opção Ultimos Erros > não deverá aparecer mensagem de erro.",
    "Abrir o aplicativo Ajuda > Selecionar a opção Ultimos Erros > deverá aparecer mensagem ou mensagens de erro (ex: senha invalida na hora que realizado pagamento).",
    "Abrir o aplicativo Ajuda > Selecionar a opção Ultimos Erros > deverá aparecer uma ou mais mensagens de erro > clicar em imprimir erros > devera ser impresso a filipeta com os erros reportados.",

    # 122 a 124 (Seção Calculadora)
    "Abrir o aplicativo pagamento e realizar todos os tipos de transação matemática.",
    "Abrir o aplicativo pagamento > realizar uma transação matematica > com o resultado obtido clicar em pagar > realizar o pagaento.",
    "Abrir o aplicativo pagemto > digitar um valor (sem realizar transação matematica) > clicar em pagar e realizar o pagamento.",

    # 125 a 132 (Seção Simulador de Vendas)
    "Abrir o aplicativo Simulador de vendas > sair do aplicativo simulador de vendas pelo touch.",
    "Abrir o aplicativo Simulador de vendas > sair do aplicativo simulador de vendas pelo teclado físico.",
    "Abrir o aplicativo Simulador de vendas > Simular uma venda no Debito.",
    "Abrir o aplicativo Simulador de vendas > Simular uma venda no Crédito.",
    "Abrir o aplicativo Simulador de vendas > Simular uma venda no Credito parcelado.",
    "Abrir o aplicativo Simulador de vendas > simular uma venda no debito/ credito/ credito parcelado > clicar no toggle Receber valor integral e verificar se há mudanças no valor > deverá haver.",
    "Abrir o aplicativo Simulador de vendas > Simular vendas de 13x a 18x.",
    "Abrir o aplicativo Simulador de vendas > Simular uma venda e pagar no Debito / Credito e Credito Parcelado.",

    # 133 a 141 (Seção Reimpressão/Recibos)
    "Realizar uma Pagamento > Atualizar o aplicativo / kernel > Após os dois tipos de atualização > verificar se é possivel realizar uma reimpressão de um pagamento que foi feito anteriormente a elas.",
    "Realizar uma Cancelamento > Atualizar o aplicativo / kernel > Após os dois tipos de atualização > verificar se é possivel realizar uma reimpressão de um Cancelamento que foi feito anteriormente a elas.",
    "Deverá desativar no aplicativo ajustes a via do lojista > Relizar um pagamento onde a via do lojista não foi impressa devido a desativação > Abrir o app Reimpressão e realizar a reimpressão da via do lojista que não foi impressa.",
    "Abrir o aplicativo de Pagamento > realizar um pagamento e NÃO IMPRIMIR a via do cliente > após isso ir no aplicativo Reimpressão e realizara via da via do cliente do pagamento que não foi impressa.",
    "Deverá desativar no aplicativo ajustes a via do lojista > Relizar um cancelamento onde a via do lojista não foi impressa devido a desativação > Abrir o app Reimpressão e realizar a reimpressão da via do lojista que não foi impressa.",
    "Abrir o aplicativo de Cancelamento > realizar um cancelamento e NÃO IMPRIMIR a via do cliente > após isso ir no aplicativo Reimpressão e realizara via da via do cliente do cancelamento que não foi impressa.",
    "Dado que realizou um pagamento > abrir o aplicativo Reimpressão e reenviar a via do SMS para o cliente.",
    "Dado que realizou um cancelamento > abrir o aplicativo Reimpressão e reenviar a via do SMS para o cliente.",
    "Dado que não realizei nenhum pagamento ou cancelamento no POS > abrir o aplicativo reimpreesão e verificar que não existirá reimpressões a serem realizadas.",

    # 142 a 150 (Seção Relatório)
    "Abrir o aplicativo Relatório > verificar transações realizados no dia atual.",
    "Abrir o aplicativo Relatório > verificar transações realizadas no dia de Ontem , Ultimos 7 dias , Ultimos 30 dias, Esse mês e Personalizado.",
    "Abrir o aplicativo Relatório > Devera existirem transações a serem exibidas  > realizar uma atualização do proprio aplicativo ou kernel > verificar se as transações que estavam anteriormente a atualização se mantiveram no aplicativo.",
    "Abrir o aplicativo Relatório > Clicar em 'Ver Detalhado' > Imprimir Relatório Detalhado.",
    "Abrir o aplicativo Relatório > Clicar em imprimir relatório consolidado.",
    "Abrir o aplicativo Relatório > Devera ter sido feita 45 ou mais transações > entrar na opção Historico de vendas > deverão ser impressas as ultimas 45 transações.",
    "Abrir o aplicativo Relatorio > selecionar a opção enviar por email (deverá existir transações no periodo selecionado).",
    "Abrir o aplicativo Relatorio > Consolidado e Detalhado Todos os tipos de transações devem ter sido realizadas e devem estar descriminadas conforme o tipo.",
    "Realizar uma venda em dinheiro > Abrir o aplicativo Relatorio > Deverá aparecer que foi realizada a venda em dinheiro.",

    # 151 a 156 (Fechamento)
    "Abrir o aplicativo Relatórios> Fechamento rápido  > não deve ter sido feito nenhum fechamento no POS > Clicar em Continuar > Colocar data e hora em formatos incorretos > deverá aparecer uma mensagem de erro de hora e data invalida.",
    "Abrir o aplicativo Relatórios> Fechamento rápido > não deve ter sido feito nenhum fechamento no POS > Clicar em Continuar > Colocar data e hora em formatos corretos > irá aparecer o fechamento > clicar em imprimir.",
    "Abrir o aplicativo Relatórios> Fechamento rápido > já ter realizado um fechamento no POS > Clicar em Fazer Fechamento > Clicar em imprimir.",
    "Abrir o aplicativo Relatórios> Fechamento rápido > Últimos fechamentos> já ter realizado pelo menos um fechamento no POS > Clicar em Fechamentos Realizados > selecionar e imprimir um fechamento ja realizado.",
    "Abrir o aplicativo Relatórios> Fechamento rápido > Realizar um Fechamento qualquer.",
    "Abrir o aplicativo Relatórios> Fechamento rápido > no momento da impressão deverá ou estar com o Slot aberto ou sem Bobina no Slot > aparecerá uma mensagem de erro na impressão.",

    # 157 a 161 (Loja)
    "Acessar o Menu através da tecla Enter ou o atalho na tela principal > Verificar se existe o aplicativo Lojas aplicativo.",
    "Abrir o aplicativo Lojas aplicativo > verificar se é disponibilzado listagem de aplicativos para efetuar download.",
    "Abrir o aplicativo  Lojas aplicativo > verificar se é disponibilzado listagem de aplicativos para efetuar download > selecionar uma aplicação e instalar (os aplicativos que já estão no POS quando ativado não deverão aparecer nesta listagem).",
    "Abrir o aplicativo  Lojas aplicativo > verificar se na aba Instalados aparecem os aplicativos Nativos (aplicativos que já estão no POS quando ativado).",
    "Abrir o aplicativo  Lojas aplicativo > efetuar download de um aplicativo > efetuar uma atualização do kernel > Verificar se o aplicativo continua instalado após a atualização.",

    # 162 a 164 (Novidades)
    "Após realizar a ativação do POS > verificar se abre as Novidades assim que iniciado.",
    "Após realizar uma atualização do kernel > verificar se abre as Novidades assim que iniciado.",
    "Acessar o Menu através da tecla Enter ou o atalho na tela principal > Clicar no aplicativo Novidades."
]